export const CLINICAL_REVIEW_COPY = {
  differentialTitle: 'Differential Review',
  differentialSubtitle:
    'Consider relevant alternative diagnoses before proceeding. This helps confirm the most appropriate pathway.',
  differentialHelper: 'Expand an item to review distinguishing features and supporting evidence.',
  reviewedLabel: 'I have reviewed the relevant differential diagnoses.',
  reviewedCollapsed: 'Reviewed',
  choosePathway: 'Choose a different pathway',
  choosePathwayTitle: 'Choose a different pathway?',
  choosePathwayBody:
    'This will return you to the pathway-selection step. Your completed information will be preserved.',
  choosePathwayCancel: 'Cancel',
  choosePathwayConfirm: 'Go back',
  addDifferential: 'Add another differential diagnosis',
  addDifferentialHint: 'Enter a condition not listed above (optional).',
  addDifferentialTitle: 'Add another differential diagnosis',
  searchPlaceholder: 'Search for a condition (e.g. oral candidiasis)…',
  or: 'or',
  namePlaceholder: 'Enter condition name…',
  add: 'Add',
  cancel: 'Cancel',
  save: 'Save',
  edit: 'Edit',
  remove: 'Remove',
  addedByPharmacist: 'Added by pharmacist',
  removeTitle: 'Remove this differential?',
  removeBody: 'This removes the alternative you added. The selected pathway will not change.',
  alreadyListed: 'Already listed',
  searchHint: 'Search or enter a condition and add to the list.',
  distinguishing: 'Distinguishing features',
  whyConsider: 'Why consider this?',
  remember: 'Remember',
  keyReferences: 'Key references',
  viewFullReferences: 'View full references',
  noReferences: 'No references are mapped to this item.',
  evidenceReview: 'Evidence & review',
  guidelineSources: 'Guideline sources',
  developmentReview: 'Development & review',
  sourcesTitle: 'Clinical Sources',
  noSectionSources: 'No published sources are listed for this section.',
  aboutGovernance: 'About our clinical content governance',
  contentReviewedBy: 'Content reviewed by',
  lastReviewed: 'Last reviewed',
  redFlagsTitle: 'Red Flags & Safety Screening',
  redFlagsSubtitle:
    'Check for findings that may require referral or prevent treatment through this pathway.',
  redFlagsLockedHint: 'Review the relevant differential diagnoses to continue to safety screening.',
  confirmNone: 'Confirm none present',
  confirmNoneHint: 'Confirms that all listed red-flag findings were assessed and are absent.',
  nonePresentTitle: 'All set',
  nonePresentBody: 'All listed red flags marked as absent.',
  undo: 'Undo',
  resetAnswers: 'Reset answers',
  resetTitle: 'Reset red-flag answers?',
  resetBody:
    'This clears Yes and No answers and any actions recorded for those answers. Differential review is kept.',
  why: 'Why?',
  whyTitle: 'Why this matters',
  answered: (answered: number, total: number) => `${answered} of ${total} answered`,
  alternatives: (count: number) =>
    `${count} alternative${count === 1 ? '' : 's'}`,
  continue: 'Continue to Treatment Options',
  back: 'Back to Presentation Review',
  refer: 'Refer / stop pathway',
  continueWithJudgment: 'Continue with Clinical Judgment',
  viewGuidance: 'View guidance',
  unresolvedSafety:
    'A safety finding still needs a referral decision or documented clinical judgment.',
  differentialIncomplete: 'Confirm you have reviewed the relevant differential diagnoses.',
  safetyIncomplete: 'Answer each listed red-flag question before continuing.',
  safetyMustBeAbsent:
    'Mark every red-flag finding as No before continuing to treatment. Use Confirm none present, or answer each question.',
  noRedFlags: 'This pathway has no red-flag checklist. You can continue once differential review is complete.',
  emptyDifferentials: 'This pathway has no alternative diagnoses listed. You can add one if needed.',
  frequencyCommon: 'Common',
  frequencyLessCommon: 'Less common',
  frequencyRare: 'Rare',
} as const;

const FORBIDDEN = [
  /I have considered the listed alternative diagnoses/i,
  /AI suggestion/i,
  /Change clinical assessment/i,
  /Re-diagnose/i,
  /Is the following present/i,
  /No to all/i,
  /Continue to Prescribing/i,
  /Back to Patient/i,
];

export function clinicalReviewCopyHasForbiddenLanguage(text: string): boolean {
  return FORBIDDEN.some((pattern) => pattern.test(text));
}
