export const PATIENT_INFO_COPY = {
  title: 'Patient information',
  subtitle: 'Confirm the information needed for this assessment.',
  requiredTitle: 'Required before continuing',
  requiredBody: 'Complete all required sections and fields (marked in orange).',
  snapshotTitle: 'Patient snapshot',
  snapshotHelper: 'Basic patient details are required',
  dob: 'Date of birth',
  dobUnavailable: 'Date of birth unavailable',
  dobUnavailableHint: 'Enter age instead',
  age: 'Age',
  years: 'Years',
  sex: 'Sex at birth',
  backgroundTitle: 'Patient background',
  backgroundHelper: 'Complete the following information.',
  allergies: 'Allergies',
  allergiesHelper: 'Document known allergies or confirm none.',
  allergiesNone: 'No known allergies',
  allergiesNoneAria: 'Confirm no known allergies. Required if no allergy is added.',
  medications: 'Current medications',
  medicationsHelper: 'Document current medications or confirm none.',
  medicationsNone: 'No current medications',
  medicationsNoneAria: 'Confirm no current medications. Required if no medication is added.',
  conditions: 'Medical conditions',
  conditionsHelper: 'Document relevant conditions or confirm none.',
  conditionsNone: 'No known conditions',
  conditionsNoneAria: 'Confirm no known conditions. Required if no condition is added.',
  lifestyle: 'Lifestyle',
  lifestyleHelper: 'Smoking, alcohol, and other relevant lifestyle factors.',
  addLifestyle: 'Add lifestyle',
  optional: 'Optional',
  add: 'Add',
  fromConsultation: 'From consultation',
  labsTitle: 'Labs & Vitals',
  labsHelper: 'Add relevant lab values and vital signs if available.',
  recentLabs: 'Recent lab results',
  vitals: 'Vitals',
  vitalsHelper: 'Record if available.',
  back: 'Back to assessment',
  confirm: 'Confirm patient information →',
  noneConfirmTitle: 'Clear existing entries?',
  noneConfirmBody: 'This will remove the values already added for this row.',
  noneConfirmAction: 'Clear entries',
} as const;
