-- Adapt module consultation progress markers
ALTER TYPE "ConsultationStep" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_AND_REASON';
ALTER TYPE "ConsultationStep" ADD VALUE IF NOT EXISTS 'PATIENT_ASSESSMENT';
ALTER TYPE "ConsultationStep" ADD VALUE IF NOT EXISTS 'PROPOSED_ADAPTATION';
ALTER TYPE "ConsultationStep" ADD VALUE IF NOT EXISTS 'DOCUMENTS_AND_COMPLETE';
