export type PaletteId = 'cyan' | 'slate' | 'indigo' | 'rose' | 'emerald' | 'ocean' | 'violet' | 'noir';

export interface PaletteTokens {
  background: string;
  foreground: string;
  card: string;
  'card-foreground': string;
  primary: string;
  'primary-foreground': string;
  secondary: string;
  'secondary-foreground': string;
  muted: string;
  'muted-foreground': string;
  accent: string;
  'accent-foreground': string;
  destructive: string;
  'destructive-foreground': string;
  border: string;
  input: string;
  ring: string;
  sidebar: string;
  'sidebar-foreground': string;
  'sidebar-active': string;
  'sidebar-muted': string;
  success: string;
  'success-muted': string;
  warning: string;
  'warning-muted': string;
  'warning-foreground': string;
  'page-gradient-1': string;
  'page-gradient-2': string;
}

export interface ThemePalette {
  id: PaletteId;
  name: string;
  description: string;
  /** Preview swatches: [primary, accent surface, neutral] */
  swatches: [string, string, string];
  light: PaletteTokens;
  dark: PaletteTokens;
}

export const THEME_PALETTES: ThemePalette[] = [
  {
    id: 'cyan',
    name: 'Cyan Brand',
    description:
      'Soft clinical surfaces, #006875 primary, and black text — SafeScribe prescribing workflow brand.',
    swatches: ['#006875', '#ffffff', '#0a0a0a'],
    light: {
      background: '#f7fafb',
      foreground: '#0a0a0a',
      card: '#ffffff',
      'card-foreground': '#0a0a0a',
      primary: '#006875',
      'primary-foreground': '#ffffff',
      secondary: '#eef6f7',
      'secondary-foreground': '#0a4f58',
      muted: '#f1f5f6',
      'muted-foreground': '#5b6b73',
      accent: '#e6f4f1',
      'accent-foreground': '#006875',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e0e8ea',
      input: '#e0e8ea',
      ring: '#006875',
      sidebar: '#ffffff',
      'sidebar-foreground': '#0a0a0a',
      'sidebar-active': '#e6f4f1',
      'sidebar-muted': '#8a9aa3',
      success: '#0f766e',
      'success-muted': '#f0fdfa',
      warning: '#d97706',
      'warning-muted': '#fffbeb',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(0, 104, 117, 0.07)',
      'page-gradient-2': 'rgba(0, 104, 117, 0.03)',
    },
    dark: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#111111',
      'card-foreground': '#fafafa',
      primary: '#2dd4bf',
      'primary-foreground': '#042f2e',
      secondary: '#1a1a1a',
      'secondary-foreground': '#e5e5e5',
      muted: '#171717',
      'muted-foreground': '#a3a3a3',
      accent: '#134e4a',
      'accent-foreground': '#99f6e4',
      destructive: '#f87171',
      'destructive-foreground': '#ffffff',
      border: '#262626',
      input: '#262626',
      ring: '#2dd4bf',
      sidebar: '#0a0a0a',
      'sidebar-foreground': '#fafafa',
      'sidebar-active': '#134e4a',
      'sidebar-muted': '#737373',
      success: '#2dd4bf',
      'success-muted': '#042f2e',
      warning: '#fbbf24',
      'warning-muted': '#422006',
      'warning-foreground': '#0a0a0a',
      'page-gradient-1': 'rgba(45, 212, 191, 0.08)',
      'page-gradient-2': 'rgba(21, 94, 117, 0.12)',
    },
  },
  {
    id: 'slate',
    name: 'Slate Pro',
    description: 'Clean and neutral with a sky-blue accent. A solid alternate for everyday use.',
    swatches: ['#0ea5e9', '#f1f5f9', '#64748b'],
    light: {
      background: '#f8fafc',
      foreground: '#0f172a',
      card: '#ffffff',
      'card-foreground': '#0f172a',
      primary: '#0284c7',
      'primary-foreground': '#ffffff',
      secondary: '#f1f5f9',
      'secondary-foreground': '#334155',
      muted: '#f1f5f9',
      'muted-foreground': '#64748b',
      accent: '#e0f2fe',
      'accent-foreground': '#075985',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#0284c7',
      sidebar: '#ffffff',
      'sidebar-foreground': '#0f172a',
      'sidebar-active': '#e0f2fe',
      'sidebar-muted': '#94a3b8',
      success: '#059669',
      'success-muted': '#ecfdf5',
      warning: '#d97706',
      'warning-muted': '#fffbeb',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(2, 132, 199, 0.06)',
      'page-gradient-2': 'rgba(2, 132, 199, 0.02)',
    },
    dark: {
      background: '#0b1120',
      foreground: '#f8fafc',
      card: '#111827',
      'card-foreground': '#f8fafc',
      primary: '#38bdf8',
      'primary-foreground': '#082f49',
      secondary: '#1e293b',
      'secondary-foreground': '#e2e8f0',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#0c4a6e',
      'accent-foreground': '#bae6fd',
      destructive: '#f87171',
      'destructive-foreground': '#ffffff',
      border: '#1e293b',
      input: '#334155',
      ring: '#38bdf8',
      sidebar: '#0f172a',
      'sidebar-foreground': '#f8fafc',
      'sidebar-active': '#0c4a6e',
      'sidebar-muted': '#64748b',
      success: '#34d399',
      'success-muted': '#052e16',
      warning: '#fbbf24',
      'warning-muted': '#422006',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(56, 189, 248, 0.08)',
      'page-gradient-2': 'rgba(56, 189, 248, 0.03)',
    },
  },
  {
    id: 'indigo',
    name: 'Indigo SaaS',
    description: 'Modern indigo highlights. Works well for dashboards and admin screens.',
    swatches: ['#4f46e5', '#eef2ff', '#71717a'],
    light: {
      background: '#fafafa',
      foreground: '#18181b',
      card: '#ffffff',
      'card-foreground': '#18181b',
      primary: '#4f46e5',
      'primary-foreground': '#ffffff',
      secondary: '#f4f4f5',
      'secondary-foreground': '#3f3f46',
      muted: '#f4f4f5',
      'muted-foreground': '#71717a',
      accent: '#eef2ff',
      'accent-foreground': '#3730a3',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e4e4e7',
      input: '#e4e4e7',
      ring: '#4f46e5',
      sidebar: '#ffffff',
      'sidebar-foreground': '#18181b',
      'sidebar-active': '#eef2ff',
      'sidebar-muted': '#a1a1aa',
      success: '#059669',
      'success-muted': '#ecfdf5',
      warning: '#d97706',
      'warning-muted': '#fffbeb',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(79, 70, 229, 0.05)',
      'page-gradient-2': 'rgba(79, 70, 229, 0.02)',
    },
    dark: {
      background: '#09090b',
      foreground: '#fafafa',
      card: '#18181b',
      'card-foreground': '#fafafa',
      primary: '#6366f1',
      'primary-foreground': '#ffffff',
      secondary: '#27272a',
      'secondary-foreground': '#e4e4e7',
      muted: '#27272a',
      'muted-foreground': '#a1a1aa',
      accent: '#1e1b4b',
      'accent-foreground': '#c7d2fe',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#27272a',
      input: '#3f3f46',
      ring: '#818cf8',
      sidebar: '#18181b',
      'sidebar-foreground': '#fafafa',
      'sidebar-active': '#1e1b4b',
      'sidebar-muted': '#71717a',
      success: '#34d399',
      'success-muted': '#052e16',
      warning: '#f59e0b',
      'warning-muted': '#422006',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(129, 140, 248, 0.07)',
      'page-gradient-2': 'rgba(129, 140, 248, 0.03)',
    },
  },
  {
    id: 'rose',
    name: 'Rose Clinical',
    description: 'Warm burgundy tones — calm and professional, suited to pharmacy care.',
    swatches: ['#9f1239', '#fff1f2', '#78716c'],
    light: {
      background: '#fafaf9',
      foreground: '#1c1917',
      card: '#ffffff',
      'card-foreground': '#1c1917',
      primary: '#9f1239',
      'primary-foreground': '#ffffff',
      secondary: '#f5f5f4',
      'secondary-foreground': '#44403c',
      muted: '#f5f5f4',
      'muted-foreground': '#78716c',
      accent: '#ffe4e6',
      'accent-foreground': '#9f1239',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e7e5e4',
      input: '#e7e5e4',
      ring: '#9f1239',
      sidebar: '#ffffff',
      'sidebar-foreground': '#1c1917',
      'sidebar-active': '#fff1f2',
      'sidebar-muted': '#a8a29e',
      success: '#059669',
      'success-muted': '#ecfdf5',
      warning: '#d97706',
      'warning-muted': '#fffbeb',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(159, 18, 57, 0.05)',
      'page-gradient-2': 'rgba(159, 18, 57, 0.02)',
    },
    dark: {
      background: '#0c0a09',
      foreground: '#fafaf9',
      card: '#1c1917',
      'card-foreground': '#fafaf9',
      primary: '#fb7185',
      'primary-foreground': '#4c0519',
      secondary: '#292524',
      'secondary-foreground': '#e7e5e4',
      muted: '#292524',
      'muted-foreground': '#a8a29e',
      accent: '#4c0519',
      'accent-foreground': '#fecdd3',
      destructive: '#f87171',
      'destructive-foreground': '#ffffff',
      border: '#292524',
      input: '#44403c',
      ring: '#fb7185',
      sidebar: '#1c1917',
      'sidebar-foreground': '#fafaf9',
      'sidebar-active': '#4c0519',
      'sidebar-muted': '#78716c',
      success: '#34d399',
      'success-muted': '#052e16',
      warning: '#fbbf24',
      'warning-muted': '#422006',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(251, 113, 133, 0.08)',
      'page-gradient-2': 'rgba(251, 113, 133, 0.03)',
    },
  },
  {
    id: 'emerald',
    name: 'Emerald Care',
    description: 'Soft green tones for a calm, trustworthy feel in daily pharmacy work.',
    swatches: ['#059669', '#ecfdf5', '#6b7280'],
    light: {
      background: '#f9fafb',
      foreground: '#111827',
      card: '#ffffff',
      'card-foreground': '#111827',
      primary: '#059669',
      'primary-foreground': '#ffffff',
      secondary: '#f3f4f6',
      'secondary-foreground': '#374151',
      muted: '#f3f4f6',
      'muted-foreground': '#6b7280',
      accent: '#d1fae5',
      'accent-foreground': '#065f46',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#059669',
      sidebar: '#ffffff',
      'sidebar-foreground': '#111827',
      'sidebar-active': '#ecfdf5',
      'sidebar-muted': '#9ca3af',
      success: '#059669',
      'success-muted': '#ecfdf5',
      warning: '#d97706',
      'warning-muted': '#fffbeb',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(5, 150, 105, 0.05)',
      'page-gradient-2': 'rgba(5, 150, 105, 0.02)',
    },
    dark: {
      background: '#030712',
      foreground: '#f9fafb',
      card: '#111827',
      'card-foreground': '#f9fafb',
      primary: '#34d399',
      'primary-foreground': '#064e3b',
      secondary: '#1f2937',
      'secondary-foreground': '#e5e7eb',
      muted: '#1f2937',
      'muted-foreground': '#9ca3af',
      accent: '#064e3b',
      'accent-foreground': '#a7f3d0',
      destructive: '#f87171',
      'destructive-foreground': '#ffffff',
      border: '#1f2937',
      input: '#374151',
      ring: '#34d399',
      sidebar: '#111827',
      'sidebar-foreground': '#f9fafb',
      'sidebar-active': '#064e3b',
      'sidebar-muted': '#6b7280',
      success: '#34d399',
      'success-muted': '#052e16',
      warning: '#fbbf24',
      'warning-muted': '#422006',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(52, 211, 153, 0.08)',
      'page-gradient-2': 'rgba(52, 211, 153, 0.03)',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean Soft',
    description: 'Softer cyan-teal variant — same family as Cyan Brand with a cooler wash.',
    swatches: ['#0e7490', '#ecfeff', '#0a0a0a'],
    light: {
      background: '#f8fcfd',
      foreground: '#0a0a0a',
      card: '#ffffff',
      'card-foreground': '#0a0a0a',
      primary: '#0e7490',
      'primary-foreground': '#ffffff',
      secondary: '#ecfeff',
      'secondary-foreground': '#155e75',
      muted: '#f0f9fb',
      'muted-foreground': '#5b6b73',
      accent: '#cffafe',
      'accent-foreground': '#155e75',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#d7e8ed',
      input: '#d7e8ed',
      ring: '#0e7490',
      sidebar: '#ffffff',
      'sidebar-foreground': '#0a0a0a',
      'sidebar-active': '#ecfeff',
      'sidebar-muted': '#8a9aa3',
      success: '#0f766e',
      'success-muted': '#f0fdfa',
      warning: '#d97706',
      'warning-muted': '#fffbeb',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(14, 116, 144, 0.07)',
      'page-gradient-2': 'rgba(21, 94, 117, 0.03)',
    },
    dark: {
      background: '#020617',
      foreground: '#f8fafc',
      card: '#0f172a',
      'card-foreground': '#f8fafc',
      primary: '#22d3ee',
      'primary-foreground': '#083344',
      secondary: '#1e293b',
      'secondary-foreground': '#e2e8f0',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#155e75',
      'accent-foreground': '#a5f3fc',
      destructive: '#f87171',
      'destructive-foreground': '#ffffff',
      border: '#1e293b',
      input: '#334155',
      ring: '#22d3ee',
      sidebar: '#0f172a',
      'sidebar-foreground': '#f8fafc',
      'sidebar-active': '#155e75',
      'sidebar-muted': '#64748b',
      success: '#2dd4bf',
      'success-muted': '#042f2e',
      warning: '#fbbf24',
      'warning-muted': '#422006',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(34, 211, 238, 0.08)',
      'page-gradient-2': 'rgba(21, 94, 117, 0.1)',
    },
  },
  {
    id: 'violet',
    name: 'Violet Studio',
    description: 'Soft violet on neutral greys. Polished and contemporary.',
    swatches: ['#7c3aed', '#f5f3ff', '#737373'],
    light: {
      background: '#fafafa',
      foreground: '#171717',
      card: '#ffffff',
      'card-foreground': '#171717',
      primary: '#7c3aed',
      'primary-foreground': '#ffffff',
      secondary: '#f5f5f5',
      'secondary-foreground': '#404040',
      muted: '#f5f5f5',
      'muted-foreground': '#737373',
      accent: '#f5f3ff',
      'accent-foreground': '#5b21b6',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#7c3aed',
      sidebar: '#ffffff',
      'sidebar-foreground': '#171717',
      'sidebar-active': '#f5f3ff',
      'sidebar-muted': '#a3a3a3',
      success: '#059669',
      'success-muted': '#ecfdf5',
      warning: '#d97706',
      'warning-muted': '#fffbeb',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(124, 58, 237, 0.05)',
      'page-gradient-2': 'rgba(124, 58, 237, 0.02)',
    },
    dark: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#171717',
      'card-foreground': '#fafafa',
      primary: '#a78bfa',
      'primary-foreground': '#2e1065',
      secondary: '#262626',
      'secondary-foreground': '#e5e5e5',
      muted: '#262626',
      'muted-foreground': '#a3a3a3',
      accent: '#2e1065',
      'accent-foreground': '#ddd6fe',
      destructive: '#f87171',
      'destructive-foreground': '#ffffff',
      border: '#262626',
      input: '#404040',
      ring: '#a78bfa',
      sidebar: '#171717',
      'sidebar-foreground': '#fafafa',
      'sidebar-active': '#2e1065',
      'sidebar-muted': '#737373',
      success: '#34d399',
      'success-muted': '#052e16',
      warning: '#fbbf24',
      'warning-muted': '#422006',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(167, 139, 250, 0.08)',
      'page-gradient-2': 'rgba(167, 139, 250, 0.03)',
    },
  },
  {
    id: 'noir',
    name: 'Noir Mono',
    description: 'High-contrast black and white. Minimal and clinical — buttons stand out clearly.',
    swatches: ['#ffffff', '#121212', '#737373'],
    light: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      'card-foreground': '#0a0a0a',
      primary: '#0a0a0a',
      'primary-foreground': '#ffffff',
      secondary: '#f5f5f5',
      'secondary-foreground': '#171717',
      muted: '#f5f5f5',
      'muted-foreground': '#737373',
      accent: '#0a0a0a',
      'accent-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#0a0a0a',
      sidebar: '#fafafa',
      'sidebar-foreground': '#0a0a0a',
      'sidebar-active': '#0a0a0a',
      'sidebar-muted': '#a3a3a3',
      success: '#16a34a',
      'success-muted': '#f0fdf4',
      warning: '#d97706',
      'warning-muted': '#fffbeb',
      'warning-foreground': '#ffffff',
      'page-gradient-1': 'rgba(0, 0, 0, 0.02)',
      'page-gradient-2': 'rgba(0, 0, 0, 0.01)',
    },
    dark: {
      background: '#000000',
      foreground: '#fafafa',
      card: '#0a0a0a',
      'card-foreground': '#fafafa',
      primary: '#ffffff',
      'primary-foreground': '#0a0a0a',
      secondary: '#171717',
      'secondary-foreground': '#e5e5e5',
      muted: '#171717',
      'muted-foreground': '#a3a3a3',
      accent: '#f5f5f5',
      'accent-foreground': '#0a0a0a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#262626',
      input: '#262626',
      ring: '#ffffff',
      sidebar: '#121212',
      'sidebar-foreground': '#fafafa',
      'sidebar-active': '#f5f5f5',
      'sidebar-muted': '#737373',
      success: '#22c55e',
      'success-muted': '#052e16',
      warning: '#f59e0b',
      'warning-muted': '#422006',
      'warning-foreground': '#0a0a0a',
      'page-gradient-1': 'rgba(255, 255, 255, 0.03)',
      'page-gradient-2': 'rgba(255, 255, 255, 0.01)',
    },
  },
];

export const DEFAULT_PALETTE_ID: PaletteId = 'cyan';

export function getPaletteById(id: PaletteId | string): ThemePalette {
  return THEME_PALETTES.find((p) => p.id === id) ?? THEME_PALETTES[0];
}

export function applyPaletteTokens(tokens: PaletteTokens, root: HTMLElement) {
  (Object.entries(tokens) as [keyof PaletteTokens, string][]).forEach(([key, value]) => {
    root.style.setProperty(`--${key}`, value);
  });
}
